# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: PLAIT
subtitle: Programming Languages for Approachable and Inclusive Tools
subsubtitle: A UC Berkeley EECS lab at the intersection of PL and HCI.
descriptionshort: >- # this means to ignore newlines until "baseurl:"
  PLAIT Lab combines techniques from Programming Languages and Human-Computer Interaction 
  to invent usable programming tools&#8212;especially programming tools to help teams 
  working for social good.
descriptionlong: >- # this means to ignore newlines until "baseurl:"
  PLAIT Lab combines techniques from Programming Languages and Human-Computer 
  Interaction to invent usable programming tools&#8212;especially programming 
  tools to help teams working for social good.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://plait-lab.org" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: PLAITlab
github_username:  plait-lab
title_image: /assets/images/plaitlab.png

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

themes:
  - title: PL for Social Good
    description: We invent usable programming tools to help teams working for social good&#8212;social scientists, journalists, lawyers, domain experts focused on marginalized groups.  (Working for social good and struggling to write code or process data?  Get in touch!) 
  - title: PL + HCI
    description: We combine techniques from Programming Languages and Human-Computer Interaction to make programming languages and programming tools that work better for coders and non-coders alike.

people:
  - first: Sarah E.
    last: Chasins
    website: https://schasins.com/
    role: Faculty
    roleindex: 0
    img: /assets/images/headshots/schasins.jpg
  - first: Justin
    last: Lubin
    website: https://jlubin.net/
    role: Ph.D. Student
    roleindex: 1
    img: /assets/images/headshots/jlubin.jpg
  - first: Gabriel
    last: Matute
    website: https://about.gmatute.dev/
    role: Ph.D. Student
    roleindex: 1
    img: /assets/images/headshots/gmatute.jpg
  - first: Lisa
    last: Rennels
    website: https://www.lisarennels.com/
    role: Energy & Resources Group Ph.D. Student, EECS M.Sc.
    roleindex: 2
    img: /assets/images/headshots/lrennels.jpeg
  - first: Rolando
    last: Garcia
    website: https://rlnsanz.github.io
    role: Ph.D. Student
    roleindex: 1
    img: /assets/images/headshots/rogarcia.jpeg
  - first: Rajavi
    last: Mishra
    role: Undergraduate Student
    roleindex: 3
    img: /assets/images/headshots/rmishra.jpg
  - first: Slim "Sarah"
    last: Lim
    website: https://slim.computer/
    role: Ph.D. Student
    roleindex: 1
    img: /assets/images/headshots/slim.jpeg
  - first: Hellina Hailu
    last: Nigatu
    website: https://hhnigatu.github.io/
    role: Ph.D. Student
    roleindex: 1
    img: /assets/images/headshots/hnigatu.jpeg
  - first: Parker
    last: Ziegler
    website: https://parkerziegler.com/
    role: Ph.D. Student
    roleindex: 1
    img: /assets/images/headshots/pziegler.png
  - first: Dhanya
    last: Jayagopal
    role: M.Sc. Student
    roleindex: 2
    img: /assets/images/headshots/djayagopal.jpeg
  - first: Rebecca
    last: Hicke
    website: https://rmatouschekh.github.io
    role: Undergraduate Student
    roleindex: 3
    img: /assets/images/headshots/rhicke.jpeg

projects:
  - name: Helena
    desc: Programming-by-demonstration tool for automating repetitive interactions with webpages.  Designed for non-programmers from the social sciences.
    img: /assets/images/projects/helena.png
    website: http://helena-lang.org/
    displayorder: 4
  - name: FLOR
    desc: "Fast Low-Overhead Recovery: Hindsight logging toolkit for model training."
    img: /assets/images/projects/flor.png
    website: https://github.com/ucbrise/flor/
    displayorder: 3
  - name: "How Statically-Typed Functional Programmers Write Code"
    desc: A grounded theory of how statically-typed functional programmers write code, covering domain modeling, type construction, focusing techniques, exploratory strategies, mental models, and expressions of intent. Ongoing work: collecting programmers&rsquo; fine-grained edit histories and developing analyses to parse and understand their behaviors over time.
    img: /assets/images/projects/stfp.png
    displayorder: 1
  - name: ""
    desc: Program transformation tools for easing the library upgrade process.  Automatic upgrade for breaking changes.
    img: /assets/images/projects/programtransform.png
    displayorder: 2



# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
